//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottyApps.EFCodeFirstProviders.Providers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScottyApps.EFCodeFirstProviders.Providers.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer does NOT match for user {0}..
        /// </summary>
        internal static string msg_AnswerNotMatched {
            get {
                return ResourceManager.GetString("msg_AnswerNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is Required for the password retrieval..
        /// </summary>
        internal static string msg_AnswerRequiredOnGetPwd {
            get {
                return ResourceManager.GetString("msg_AnswerRequiredOnGetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is required for the password reset..
        /// </summary>
        internal static string msg_AnswerRequiredOnPwdReset {
            get {
                return ResourceManager.GetString("msg_AnswerRequiredOnPwdReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can NOT decrypt a Hashed password..
        /// </summary>
        internal static string msg_CannotDecryptHashedPwd {
            get {
                return ResourceManager.GetString("msg_CannotDecryptHashedPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can NOT retrieve a Hashed password..
        /// </summary>
        internal static string msg_CannotRetrieveHashedPwd {
            get {
                return ResourceManager.GetString("msg_CannotRetrieveHashedPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email duplicates with existings..
        /// </summary>
        internal static string msg_EmailDuplication {
            get {
                return ResourceManager.GetString("msg_EmailDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Name duplicate with existings..
        /// </summary>
        internal static string msg_FuncNameDuplication {
            get {
                return ResourceManager.GetString("msg_FuncNameDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function with Name {0} does NOT exist..
        /// </summary>
        internal static string msg_FuncNotExist {
            get {
                return ResourceManager.GetString("msg_FuncNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset NOT enabled..
        /// </summary>
        internal static string msg_PwdResetNotEnabled {
            get {
                return ResourceManager.GetString("msg_PwdResetNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password retrieval NOT enabled..
        /// </summary>
        internal static string msg_PwdRetrivalNotEnabled {
            get {
                return ResourceManager.GetString("msg_PwdRetrivalNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name duplicates with existings..
        /// </summary>
        internal static string msg_RoleNameDuplication {
            get {
                return ResourceManager.GetString("msg_RoleNameDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with Name {0} does NOT exist..
        /// </summary>
        internal static string msg_RoleNotExist {
            get {
                return ResourceManager.GetString("msg_RoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is locked out..
        /// </summary>
        internal static string msg_UserLockedOut {
            get {
                return ResourceManager.GetString("msg_UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is NOT confirmed yet..
        /// </summary>
        internal static string msg_UserNotConfirmed {
            get {
                return ResourceManager.GetString("msg_UserNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Name {0} does NOT exist..
        /// </summary>
        internal static string msg_UserNotExist {
            get {
                return ResourceManager.GetString("msg_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password for User {0}..
        /// </summary>
        internal static string msg_WrongPassword {
            get {
                return ResourceManager.GetString("msg_WrongPassword", resourceCulture);
            }
        }
    }
}
